/*
AUTO-GENERATED by sysplugin-prepare on every prep run.

Snapshot of the plugin's root main.go (or main_mono.go) at generation time:
  - package renamed to "system"
  - func main() stripped (illegal in a non-main package)
  - //go:build tag PRESERVED so this file is selected under the same build
    tag as its source

DO NOT EDIT. Always regenerated when the source differs (content-aware-skip).
Edit the corresponding root main.go or main_mono.go instead. Any direct
edits here will be silently overwritten on the next sysplugin-prepare run.

Plugins with helpers split across multiple root .go files (e.g. init.go) must
move those helpers into this system/ subpackage by hand — the generator only
snapshots main.go and main_mono.go.
*/

// AUTO-GENERATED by sysplugin-prepare on first build.
//
// Snapshot of the plugin's root main.go retagged for mono. Under -tags=mono,
// main.go (tagged !mono) is excluded; this file provides the package main
// slot so the plugin directory still compiles. The mono loader does not
// actually import this file — it imports <plugin>/system — so the body is
// only consumed by tools that build the plugin directory directly.
//
// Generated ONLY when missing. Edit freely; sysplugin-prepare will not
// overwrite. Delete to force regeneration on the next build.
//
// ⚠️ THIS FILE DOES NOT TRACK main.go. Nothing re-syncs it as you build out
// this plugin, and Go silently tolerates the two drifting apart until a mono
// build actually compiles this half. If Init grows, shrinks, or renames what
// it calls in main.go, mirror the same change here (or delete both this file
// and system/main_mono.go so the next build regenerates a fresh snapshot
// from main.go) — otherwise a change that looks correct everywhere else can
// still abort a production mono release days later with an "undefined: ..."
// error nobody sees coming, because nothing here shows up in that diff. This
// exact mistake has broken more than one plugin in production already — make
// sure this file is committed (never gitignored) so drift is at least
// visible in review, and keep it in sync as main.go changes.

//go:build mono

// Package main is the entry point for the Coffee Shop portal theme plugin.
package system

import (
	sdkapi "sdk/api"

	"com.flarego.coffee-theme/app"
	"com.flarego.coffee-theme/app/theme"
)

func Init(api sdkapi.IPluginApi) error {
	app.SetupRoutes(api)
	theme.SetPortalTheme(api)
	return nil
}
