/*
AUTO-GENERATED by sysplugin-prepare on every prep run.

Snapshot of the plugin's root main.go (or main_mono.go) at generation time:
  - package renamed to "system"
  - func main() stripped (illegal in a non-main package)
  - //go:build tag PRESERVED so this file is selected under the same build
    tag as its source

DO NOT EDIT. Always regenerated when the source differs (content-aware-skip).
Edit the corresponding root main.go or main_mono.go instead. Any direct
edits here will be silently overwritten on the next sysplugin-prepare run.

Plugins with helpers split across multiple root .go files (e.g. init.go) must
move those helpers into this system/ subpackage by hand — the generator only
snapshots main.go and main_mono.go.
*/

/**
WARNING: This file system-generated, do not edit nor commit into your repo.
Edit the main.go file instead to updated this file.
*/

//go:build mono

package system

import (
	sdkapi "sdk/api"

	"com.flarego.coffee-theme/app"
	"com.flarego.coffee-theme/app/navs"
	"com.flarego.coffee-theme/app/theme"
)

func Init(api sdkapi.IPluginApi) error {
	app.SetupRoutes(api)
	navs.SetAdminNavs(api)
	theme.SetPortalTheme(api)
	return nil
}
